// resources/js/pages/Container.vue
<script lang="ts" setup>
  import { RootContainer } from '@creopse/vue'

  const { getFinalPageSections, getComponents, page } = useContent()

  const sections = getFinalPageSections()
  const components = getComponents()
</script>

<template>
  <Page>
    <AppHead />
    <RootContainer :page="page" :sections="sections" :components="components" />
  </Page>
</template>

// resources_react/js/pages/Container.tsx
import AppHead from '@/components/sections/AppHead'
import Page from '@/layouts/Page'
import { RootContainer } from '@creopse/react'
import React from 'react'

const Container: React.FC = () => {
  const { getFinalPageSections, getComponents, page } = useContent()

  const sections = getFinalPageSections()
  const components = getComponents()

  return (
    <Page>
      <AppHead />
      <RootContainer page={page} sections={sections} components={components} />
    </Page>
  )
}

export default Container
